### ISSUE TITLE
Namecheap - No id, name used twice

### ISSUE THREAD

**Issue by canihavesomecoffee** [kee-org/KeeFox#371]
Hello,

first of all I'd like to thank you for the add-on, it's really awesome.

However, I'd like to report this incompatibility with the namecheap website:

URL: https://www.namecheap.com/myaccount/login-signup.aspx
Issue: Namecheap is not using id's, and the name of the login field is used not only in the visible login-form, but also in a (by default) hidden login-form, which appears once you hover over "Sign in" on top.

When creating the entry through KeeFox it entirely messes up (several forms on the page, and it takes the "email" field at the bottom of the page as username), but even if corrected to the below settings in the "Form fields" tab of KeeFox in Keepass, it still fills in the hidden top form.

![ss 2015-02-22 at 01 19 40](https://cloud.githubusercontent.com/assets/7365586/6316674/f4dcbfac-ba30-11e4-9bf1-c35e2937bb6a.png)

Are there any possiblities to further pinpoint a given field (by class, or location), or will I have to use auto-type instead for this site?

**Comment by luckyrat** [comment]
> Are there any possibilities to further pinpoint a given field (by class, or location)

Unfortunately not. It's technically possible to implement but not a top priority.

What about just trying to log in using the home page rather than the login page? If that form at the top is always there when the page loads, it will probably work. If not, there is at least a chance of that being improved with a new KeeFox version this year.

**Comment by wforums** [comment]
Hello,

first of all, thanks for the swift reply.

The form is there on page load, however it is not a "real" form:

![ss 2015-02-22 at 07 14 55](https://cloud.githubusercontent.com/assets/7365586/6319724/d0766810-bac7-11e4-9e3b-b46bbd802756.png)

the button is actually an a element with an attached javascript listener; KeeFox does not detect it when logging in/submitting this form.

When keeping my current settings, KeeFox fills in the form, but cannot automatically submit it. I think I'll go with this; but of course it would be nice if in the future this could also perform the login.

**Comment by IBBoard** [comment]
I'm hitting part of this problem, only it seems to have got worse. I don't know what triggers it, but even on login forms then it seems to try to submit the newsletter registration in the footer, rather than logging in.

KeeFox was also filling in my username in just about every text box that it could find as well on NameCheap, but I've gone in to Keepass and deleted all of the "Form fields" entries except LoginPassword and LoginUsername and it no longer seems to fill those in.
