### ISSUE TITLE
Support 'internal' password prompts without host

### ISSUE THREAD

**Issue by Awem** [kee-org/KeeFox#379]
It would be nice to support password promts without a host URL. I think of addons like Enigmail in Thunderbird. It asks for the OpenPGP passphrase, if you access your key. The password dialog could probably be catched via Regex and/or windows indentifiers. Maybe it is also possible to interpret those prompts to target some variant of `localhost`?
_BTW, I tried to catch the dialog with the auto-fill feature. I can choose a default pattern for the Enigmail window. However, the auto-fill in is not triggered, when the window opens._

**Comment by dlech** [comment]
I just happened to be working on some other password dialogs earlier this week, so I had a quick look at this. On Linux, Thunderbird is using the OS GPG keyring support, so KeeFox cannot work in this case. The dialogs actually come from gnome-keyring or whatever is being used for a gpg agent and not from Thunderbird itself. It is probably not the case for Windows though.

The way dialog matching works for KeeFox, we need to know the exact dialog in order to fetch the strings for matching. We can't just have a general "any dialog that takes only a password" match since there would be no way to get a user name or anything else to match to.

**Comment by AW-UC** [comment]
Maybe there could be an option for the auto-fill feature, that would allow the filling to be triggered once a window with a saved custom pattern opens? Might be quite a rework though.

**Comment by luckyrat** [comment]
There's no imminent chance of this being possible but I'll keep it open in case Firefox ever makes changes to turn this into a feasible feature.
