### ISSUE TITLE
Always Show Installation Page on Linux

### ISSUE THREAD

**Issue by Binero** [kee-org/KeeFox#471]
I am running the extension on Linux, and I have followed all the steps and the extension is working, except some bugs for example detecting forms. 

Every time I boot Firefox however, the installation tab opens up for me. It shouldn't do this once its installed.

**Comment by dlech** [comment]
Which directory did you install `KeePassRPC.plgx` in? Also, what is the path to `KeePass.exe` set in the KeeFox options?

In more recent versions of KeeFox, the plgx MUST be in a subdirectory called `plugins` in the same directory as `KeePass.exe`. Otherwise you will keep seeing the install page.

@luckyrat: I've been thinking maybe we should add something to the install page that says something about this. "If you see this after KeeFox is installed, check X, Y and Z".

**Comment by luckyrat** [comment]
Yes we could but I had always meant for the plugin to be allowed in either the "plugins" subdirectory or the main KeePass.exe directory so if that isn't even happening, we should maybe look at that before updating instructions on the install page that people have evidently not read very thoroughly since it says to put the plugin in that location. Maybe the instruction on where to put the plugin is not clear enough?

**Comment by dlech** [comment]
I don't think I have tried putting the plgx in the same directory as `KeePass.exe` recently, so perhaps that works as well. But I do know if you put the plgx in any other subdirectory other than `plugins`, then KeePassRPC will load and everything will work, but you keep getting the install page every time you start Firefox.

**Comment by luckyrat** [comment]
Hmmm... maybe the right way to approach this is to scan all subfolders when we look for the plgx file. I suspect that wouldn't be a massive amount of work and I doubt there would be a measurable impact on startup performance but unfortunately Mozilla might ban us from trying that much synchronous I/O on startup. If it's not a huge amount of work it would be worth trying it but not if it is a lot of work because of the risk of us having to undo the work and cause a delay in AMO approval.

Maybe a middle ground would be to time ourselves during the scan and abort if it is too slow... but then that might just flag up the issue to the AMO reviewers unnecessarily...

**Comment by dlech** [comment]
There should only be a couple folders at most unless the user has done something really unusual.

Also, if KeeFox is connected to KeePassRPC, then you can assume that everything is installed correctly and not need to look for the plgx at all.

**Comment by luckyrat** [comment]
> There should only be a couple folders at most unless the user has done something really unusual.

Yeah that's certainly the case 99.99% of the time but AMO reviewers might consider that the impact on those 0.01% is too high. I doubt it, but they are usually strictly against synchronous I/O on the main thread so it is a slight risk.

> Also, if KeeFox is connected to KeePassRPC, then you can assume that everything is installed correctly and not need to look for the plgx at all.

Unfortunately we have to look for the plgx before we've had a chance to hear from KeePassRPC. That's mainly because we have no idea when or if we'll be able to connect so we can't wait around indefinitely (and Firefox startup times vary by minutes on different systems so there's no easy timeout value we could use).

Perhaps there's a way to delay some parts of the startup routine for some "normally long enough" timeout to at least give us a chance of avoiding the unnecessary search for the plgx file but for a solution that wouldn't solve the problem for everyone, I think that's going to end up being a good example of over-engineering.

**Comment by boldt** [comment]
I am the author of #493. 

I had the version *1.4.8.1-signed* installed from addons.mozilla.org. Today I installed the version 1.8.4 from the ppa, as described here: https://github.com/luckyrat/KeeFox/wiki/en-|-Installation-|-Linux

With this version, I do not get the "installation page" any more.

**Comment by dlech** [comment]
This is to be expected. Installing from the ppa puts the plgx in the correct directory and automatically sets the options to the correct value for you. When installing from addons.mozilla.org, you have to do these steps manually to make the install message go away.

**Comment by FNicolai** [comment]
Hello guys,
I have the exact problem you describe here on Ubuntu 14.04.02. Installed mono-complete, keepass2 and keefox via Firefox. Additionally: Everytime I install/enable the keefox-addon the second pinned tab out of four is not selectable anymore. Only a blank. I think this problem will be solved together with the actual problem. Really annoying bug but hope you can help me. Cheers

**Comment by Binero** [comment]
@FNicolai Oh is that caused by this plugin? I also have that issue.

**Comment by FNicolai** [comment]
The blank pinned tab?! I deaktivated/uninstalled and aktivated/installed keefox multiple times. Without keefox the pinned tabs worked.

**Comment by FNicolai** [comment]
After the latest update of Keefox it works now! Thanks!

**Comment by luckyrat** [comment]
I don't think there's anything we can/should do on this issue. Have I missed something?

**Comment by FNicolai** [comment]
Don't think so.

**Comment by sterys** [comment]
Well looking for the KeePassRPC.plgx in a folder called plugin in the same directory as the KeePass.exe does not work that well on linux.

When installing keepass from an ubuntu distribution there is no KeePass.exe and the executable which is called keepass2 does not reside in the same path as the rest of the installation.

So the path to the execatble is /usr/bin/keepass2 and the path to my installed plugins is /usr/lib/keepass2/plugins/KeePassRPC.plgx.

But this should maybe be addressed in an new issue on better support for native installed keepass on linux

**Comment by sterys** [comment]
I did spoke to soon. I just realised that the  /usr/bin/keepass2 is just a bash script starting KeePass.exe under mono. So I do have an KeePass.exe under /usr/lib/keepass2. So if I set that path it all works quite well

**Comment by boldt** [comment]
Unfortunately I am back to this issue. Something changed and i don't know what.

**Comment by boldt** [comment]
I also have this stange "blank" tab.

**Comment by GlennGeenen** [comment]
I had this issue on Ubuntu as well and it's solved by copying KeePassRPC.plgx in the same directory as KeePass.exe.

**Comment by rubaboo** [comment]
Had the same issue. Installed keepass2 from Debian repo, and the plugins directory name was Capitalized. This fixed it:

    cd /usr/lib/keepass2/
    mv Plugins/ plugins/
Also, you don't have to copy the file. A symbolic link works as well:

    ln -s ${HOME}/.mozilla/firefox/yourprofiledir/extensions/keefox@chris.tomlinson/deps/KeePassRPC.plgx /usr/lib/keepass2/plugins/

**Comment by ggeorgg** [comment]
I had the same problem but 
```
cd /usr/lib/keepass2/
mv Plugins/ plugins/
```
helped! Thanks a lot!
