### ISSUE TITLE
Make it compatible with WineBottler

### ISSUE THREAD

**Issue by andredasilvapinto** [kee-org/KeeFox#534]
Integration of KeeFox with KeePass running on Mono in OS X is quite good, but KeePass UI itself is completely broken in this setup, so I tried to use the second method pointed here: http://sourceforge.net/p/keepass/discussion/329220/thread/eb00d276/

And in this case I was able to get KeePass to work properly, but KeeFox doesn't seem to be able to integrate with this type of installation... I've tried to point the KeePass installation directory to the directory inside the bundled KeePass package (created with WineBottler), but it doesn't open KeePass when I tell it to launch it...

It would be great if KeeFox could support this setup as KeePass runs much better like this on OS X compared with the mono solution. Thanks.

**Comment by luckyrat** [comment]
I don't know how WineBottler does what it does but it's feasible that it could prevent interaction with other programs on the system (like Firefox/KeeFox) or that it tricks the KeePassRPC plugin to thinking it is running on Windows. KeePassRPC needs to know it running on a unix platform so it can behave differently.

I'm happy to accept any pull request that enables support for this provided that it has been tested to not break Windows or existing Mono usage on Mac/Linux but I won't be able to find time to do this myself.

It's a long-shot but perhaps worth trying the latest KeeFox version just in case it's inadvertently worked around whatever problem the WineBottler procedure is creating. https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/1.5.3

**Comment by andredasilvapinto** [comment]
thanks for replying @luckyrat . I can't install the latest version (it's not compatible with my platform), but I'm already using 1.5.3b12. The thing is that I am not even sure the problem is with the plugin itself, because KeeFox can't even start KeePass... it can start the mono based setup, but what's the path that I should use to make it run the .app created by WineBottler?

however, I agree that this is probably too much work if I am the only one requesting this. thanks anyway!

**Comment by luckyrat** [comment]
KeeFox only understands how to start KeePass.exe or mono.exe, depending on platform so I don't think you can start KeePass via a .app

If you start KeePass via some other method that will still attempt to link up with KeeFox though. So if that's not happening, there must be something about the KeePassRPC plugin running inside that .app which prevents KeeFox from talking to it.

**Comment by neothematrix** [comment]
Hi, I just finished setting up KeePass2 using Winebottler and Keefox, it works flawlessly and so far is the best setup I found. Just two comments for who is trying this:

1) make sure you install the keefox plugin from the developer section on the addon page, it's the only way to install it on a Mac, otherwise you'll get a "platform not supported" button instead of the install button.

2) After the installation, you need to copy the KeePassRPC.plgx that you can find following the KeeFox installation instructions inside the /Users/yourusername/Library/Application Support/<applicationid>/drive_c/Program Files/KeePass Password Safe 2/Plugins folder, <applicationid> is the identified you told Winebottler to give to your app. DO NOT copy the plugin inside the "winebottled" application package, Keepass won't find it! (I think this was @andredasilvapinto mistake).

3) Keefox will not recognize that you installed everything correctly and will keep the "keefox setup page" appearing every time you open firefox until you manually set the KeePass2 path inside keefox firefox option, just put any folder and the window will stop appearing.

@luckyrat great job I've been using keefox on my Windows pc and now I can flawlessly use it on my Mac too. Just a question, how come the "stable" plugin isn't marked as compatible with Mac platform? Is it just because it requires a lot of user interaction to make it work?
