### ISSUE TITLE
1.5.3 wrong filling of "https://mijn.ing.nl/internetbankieren/SesamLoginServlet"

### ISSUE THREAD

**Issue by rbraken** [kee-org/KeeFox#547]
Hi,
 after the upgrade (from 1.4.8) this site doesn't work anymore.
There are three field on the form (with random id's), they used to be filled correctly.
but now the password field is filled-in wrong.

The relevant part of debug log follows :
On this page :
Username id = id aJL4eNs9aZJcdCy5X
Password id = asLollI8jGwWh431P
a checkbox (save username) = aCxvvtiqftjPKN0Gu

Greetings Rene 

Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):INFO: Filling form fields for page 1
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):INFO: Auto-overwriting fields
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: Suitablility of putting data field 0 into form field 0 (id: ) is 21
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: Suitablility of putting data field 0 into form field 1 (id: asLollI8jGwWh431P) is 21
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):INFO: We will populate field 0 (id:)
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: _fillManyFormFields started
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: We've received the data we need
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):INFO: Filling form fields for page 1
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):INFO: Auto-overwriting fields
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: Suitablility of putting data field 0 into form field 0 (id: aJL4eNs9aZJcdCy5X) is 21
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: Suitablility of putting data field 1 into form field 0 (id: aJL4eNs9aZJcdCy5X) is 0
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: Suitablility of putting data field 0 into form field 1 (id: aCxvvtiqftjPKN0Gu) is 0
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):DEBUG: Suitablility of putting data field 1 into form field 1 (id: aCxvvtiqftjPKN0Gu) is 21
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):INFO: We will populate field 0 (id:aJL4eNs9aZJcdCy5X)
Thu Sep 17 2015 11:03:53 GMT+0200 (CEST):INFO: We will populate field 1 (id:aCxvvtiqftjPKN0Gu)

**Comment by luckyrat** [comment]
Have you asked KeeFox to save a new version of the login?

**Comment by rbraken** [comment]
yes i did (in a new empty database).

**Comment by DrIT2016** [comment]
I have the same problem, since the new 1.5 version the password of mijn.ing.nl (or ideal.ing.nl) is not filled in anymore, only the username. The site is recognized, but also clicking on the entry under keefox button, does only fill the username. Only way now is to copy password from menu item in keefox button and then paste it in password field. Older version did not have this problem, but can't use this version anymore on newer firefox. I tried deleting entry in keepass and let keefox create it again. This does work for a brief moment, but the next day after staring firefox again it is not working anymore.
Looks like Ing changes the name values of the username and password fields randomly, so maybe it has something to do with it? However then i don't understand why the older version didn't have a problem with this. Can you please look in to this as this banking site is used very often?
Thanks in advance!
