### ISSUE TITLE
Add an option to match hostname + path, but not query string

### ISSUE THREAD

**Issue by borys-p** [kee-org/KeeFox#548]
Hi,

I was always checking the "URL match" checkbox, because keefox was overwriting data in forms too often. But now this checkbox is gone, there are three options and one is missing: Hostname + path.

There are a lot of sites that add some gibberish query parameters like ?return_to=... etc. The won't be matched by "exact" match and the "hostname" will be too generic. This can be done with regexes, but a fourth option would be much easier.

**Comment by luckyrat** [comment]
The "Exact URL match" feature is still there and behaves the same way. Just choose the bottom (3rd) radio button. This setting will have been retained for each of your entries that you had set this on previously. You might want to relax the setting to the 2nd or even 1st option for some sites since KeeFox won't overwrite incorrect forms as often anymore.

If you can explain some scenarios where there needs to be a 4th option between option 2 and 3, please do so and if we find enough demand for that we can consider adding it in a future version. It's not something we'll just chuck in for an occasional use though because we don't want to overwhelm people with options on that already fairly complex panel.

**Comment by bdurrer** [comment]
Szenario: multiple internal web applications in an company, when folders instead of subdomains are used.

The third option matches the query string too. A lot of applications append the "forward to after login" to their login page, which prevents option 3 from triggering. An "full path, no query string" option would be useful here. Actually, I never saw a use for option 3, I never saw an application where the query string would help you to reliably decide which login to use (mostly because of session ids, forwardTo, etc).

**Comment by borys-p** [comment]
Exactly as @bdurrer wrote: often there is a "return to URL" appended as part of the query string together with other items, which are often random.

For example: visit http://poczta.wp.pl/ (webmail). You will be redirected to http://profil.wp.pl/login.html with a long query string, which items may be different for each request and person. And the order of query string items isn't guaranteed as well. I need to capture only "profil.wp.pl/login.html", because "profil.wp.pl" is too broad, as it has other forms which keefox shouldn't fill in.

**Comment by luckyrat** [comment]
Since this can be achieved by regex and it will clutter an already packed options panel I'm not inclined to implement this at the moment but maybe one day.

**Comment by borys-p** [comment]
Another example, which just I have just came across: every single SSO system will trigger the password save dialog with "exact" match. They all need to get the return URL in query string, as they serve many sites simultaneously. All my entries were converted to "exact" match and now KeeFox pops the password save dialog on SSO login pages, althogh the credentials were provided by himself!

**Comment by bdurrer** [comment]
I can't resist commenting this one again:
"Since this can be achieved by regex and it will clutter an already packed options panel..."

This is a weird argument, considering the fact that knowing RegEx (properly) is expert knowledge. I think the group of people who understand RegEx is much smaller than the group that cannot cope with 4 radio options o_0
