### ISSUE TITLE
Couldn't log in to the site https://login.ubuntu.com with KeeFox enabled

### ISSUE THREAD

**Issue by texpert** [kee-org/KeeFox#558]
It redirects to a page telling "Bad bot, go away! request aborted". To log in, I have to disable KeeFox.

This is an old and known issue similarly reported for Lastpass - https://www.google.com/search?client=ubuntu&channel=fs&q=list+of+send+to+ubuntu+bugs&ie=utf-8&oe=utf-8#channel=fs&q=bad+bot,+go+away!+request+aborted

Could you, please, fix this, or suggest any workaround - merely to disable KeeFox on this page (I tried to hide it from KeeFox in KeePass tab, but it didn't help)

**Comment by luckyrat** [comment]
I'm sure this has come up before. Thankfully it's only Ubuntu that feel this is a good "feature" for their website but I'm surprised they haven't fixed it by now!

Hiding the relevant entry in KeePass will prevent KeeFox from doing anything to the form so I guess that either you didn't save the database after your change or you have something else installed which triggers the same Ubuntu website bug.

A less drastic step would be to just set that particular entry to not auto-fill - at least that way you can get quick access to the entry in order to copy the username and password into the clipboard to ease the manual entry procedure.

**Comment by texpert** [comment]
Have tried again - both to disable auto-fill for this entry, and to hide it completely from KeeFox - still couldn't log in as long as KeeFox is running.
