### ISSUE TITLE
Expired entires in keepass are still listed in keefox

### ISSUE THREAD

**Issue by skibbipl** [kee-org/KeeFox#571]
I have several saved passwords for subdomains for particular site. Some of them I marked as expired in keepass. Unfortunately I'm still seeing them in keefox thus intead of 4 sites I have a list of 8. It's a liittle bit confusing.
Expired sites in keefox:
![keepass](https://cloud.githubusercontent.com/assets/4746858/10754154/295885cc-7c96-11e5-98eb-1bd57af49d59.png)
The same expired sites (marked in yellow) still accessible in keefox:
![keefox](https://cloud.githubusercontent.com/assets/4746858/10754176/438543cc-7c96-11e5-97a4-02e66534e778.png)
Can keefox filter expired entiries? I'm using latest version available.

Regards

**Comment by luckyrat** [comment]
It's not possible to do that at the moment. I expect #230 would be implemented before this since I don't see KeeFox as trying to be a full replacement for the KeePass GUI and the confusion some users will experience when not realising their login is failing to auto-fill because of an expired entry probably outweighs the benefit of completely excluding them.

**Comment by FaffeF** [comment]
It would be very helpful if the expired entries were marked somehow, like italic or strikethrough

**Comment by michue** [comment]
I could imagine an option "Include expired entries" in the "Finding entries" section, which is by default enabled.
This would not change the standard behavior of KeeFox (regarding your concern of confusing users), but enables others to hide their expired entries in autofill.

**Comment by flcdrg** [comment]
Actually, I was confused by the lack of excluding expired entries. I was hoping this would be a good way to "tidy up" my Keepass data by expiring (instead of deleting) old entries.

It would be good if you could opt in (via a configuration setting) to exclude expired entries from suggested/matching credentials
