### ISSUE TITLE
Trigger Javascript input event on filled form elements

### ISSUE THREAD

**Issue by Virakal** [kee-org/KeeFox#578]
I have found a few login forms that do their own "required field" detection in Javascript that fail to recognise that the form has been autofilled, seemingly because they rely on the "input" event and KeeFox doesn't trigger it.

Granted these sites are badly made, but I can't personally foresee any harm in triggering it.

An example would be https://id.g2a.com/, which I can only log in to with KeeFox by filling the form, then adding a character to each field and removing it again.

**Comment by luckyrat** [comment]
By putting the text directly into the form field, we avoid problems from other badly made sites which rely on the input event to manipulate what the user enters (so when we re-enter the result of that manipulation which we saved last time we logged in, the login will fail). I also know that one of the principles behind all password fillers starting out with a direct entry to the form fields is that it bypasses keyloggers, although I'm not convinced this is such a big security concern in recent years.

Like almost every aspect of password filling, this is one of those things that can only really be resolved with detailed configuration on a per-site basis. For KeeFox users that means we have to add support for the relevant configuration option and hope that they work out what it (and the other hundred options) means. I'd be surprised if commercial password fillers don't maintain their own lists of various configurations like this so that users don't have to worry about these details; I know that's what I'd do if I could afford a full time employee or two to maintain that kind of configuration.

If this sort of behaviour becomes the norm (or at least if we gather evidence that it is far more prevalent than sites which get broken by triggering an input event) we can consider switching the default behaviour to trigger an input event.
