### ISSUE TITLE
How about a tutorial for people trying to DECIDE whether to install?

### ISSUE THREAD

**Issue by TBugReporter** [kee-org/KeeFox#593]
Apparently, it's impossible to proceed past the first page of the [tutorial](http://tutorial.keefox.org/) unless you're using Firefox and KeeFox is already installed.  This means that there's no way to use this tutorial to help with the install process, and no way to gain an understanding of this addon's operation without actually installing and operating it.  Makes me long for the old days when programs came with actual physical booklets that you could read _before_ cracking open the CD case, in order to know what to expect (and yes, I was one of the few who actually read - and saved - those booklets rather than tossing them on day one.)

(Also, I'm posting this here because Zoho doesn't seem to like me right now.)

**Comment by luckyrat** [comment]
I'm not sure whether a tutorial is the most useful method to help someone decide whether to install the software - while there are some things to consider before doing so, it's not a massive burden to install new software to try it out (even for KeeFox where the need for Firefox and KeePass adds to the complexity somewhat).

In case you've not already seen both places, the add-on page and official home page should give lots of useful information to help you decide and the manual should answer more detailed questions for you.

https://addons.mozilla.org/en-US/firefox/addon/keefox/
http://keefox.org
https://github.com/luckyrat/KeeFox/wiki

I made a youtube video a few years ago that allowed a glimpse at how KeeFox works by essentially recording a run-through of the tutorial. It's now incredibly outdated and only a handful of people seemed to find it useful but on the off-chance that's the kind of thing you're looking for, here's the link: https://www.youtube.com/watch?v=H03IV87OHno

For help with the install process, there has to be an assumption that you've already got Firefox installed (and if not, KeeFox is not really best placed to help there) and that you have installed the basic add-on into Firefox (again, this is a process that is entirely unrelated to KeeFox but the links above do provide advice on this topic none-the-less since not every Firefox user has installed an add-on before). Once you've got that far, the latest version of the tutorial should be able to start offering a variety of help with the next step of the setup process (although on a typical Windows computer this is largely handled for you by KeeFox itself so you might not need any help).
