### ISSUE TITLE
Make "/Library/Frameworks/Mono.framework" the default Mono location on Mac

### ISSUE THREAD

**Issue by ywecur** [kee-org/KeeFox#594]
The current default `/usr/bin/mono` isn't the default install location used by the Mono installer. 

Switching to the actual default, `/Library/Frameworks/Mono.framework`, will limit user confusion and save for new users as mono doesn't explicitly tell the user where it's installed.

**Comment by dlech** [comment]
Wouldn't this need to be `/Library/Frameworks/Mono.framework/Versions/current/bin/mono`?

This change is needed because on El Capitan, Apple no longer lets frameworks touch `/usr/bin`. Previously mono frameworks provided a symlink there, but that is no longer the case.

You can also install mono from brew, in which case mono would be at `/usr/local/bin/mono`.

**Comment by ywecur** [comment]
On my installation it was `/Library/Frameworks/Mono.framework`

**Comment by luckyrat** [comment]
So there are at least 4 possible defaults depending upon OSX version and Mono installation method.

Without evidence that one of these possibilities is significantly more common, I don't think it makes sense to alter the current default but I'm happy to accept a pull request in this area if it can be justified so I'll keep the issue open.

**Comment by dlech** [comment]
`/Library/Frameworks/Mono.framework` is a folder, so I don't think that is a valid option since we need the path to the executable. 

Starting with OS X 10.11, `/usr/bin/mono` is no longer a valid option. Most people are going to install mono from a package rather than brew, so I think that `/Library/Frameworks/Mono.framework/Versions/Current/bin/mono` makes sense as the default. It will still work on older versions of OS X and with existing mono installs as well.

**Comment by dlech** [comment]
Looking at the [code](https://github.com/luckyrat/KeeFox/blob/2ee3cda68ff1254af07eb4c39356cda4e157c47f/Firefox%20addon/KeeFox/modules/KF.js#L337), I think that it should actually have a list of locations that it looks for (in order).

    /usr/bin/mono
    /usr/local/bin/mono
    /Library/Frameworks/Mono.framework/Versions/Current/bin/mono

This would prevent breaking on Linux, work if users compiled mono themselves or used brew on OS X and work on OS X 10.11 if mono was installed from the official package.

**Comment by fhackenberger** [comment]
Please also adapt for Linux as guessing the install location does not work on that platform either, with KeeFox working in general, but exhibiting strange bugs, like breaking session restore (#608) and making one tab invisible (#366).
