### ISSUE TITLE
How to use keefox together with multifox?

### ISSUE THREAD

**Issue by woyaojizhu8** [kee-org/KeeFox#596]
I use firefox extension multifox to manage my several profiles ,and now I try to use keefox together with multifox .But it seems that keefox is designed for single profile ,so how to keefox together with multifox ?

**Comment by luckyrat** [comment]
KeeFox is designed to connect one instance of KeeFox to one instance of KeePass but you can generally work around that limitation if you configure a pair of Firefox and KeePass to communicate on a different custom port ( https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options-%7C-KPRPC-Port ).

I have no idea how that works in the land of multifox but perhaps their support team can help you further.

I'd recommend using the KeeFox 1.6 beta because it removes the complexity of the old <KeeFox 1.3 connectivity: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/beta
