### ISSUE TITLE
Make KeeFox smarter at detecting logins and form filling

### ISSUE THREAD

**Issue by BoffinBrain** [kee-org/KeeFox#612]
At the moment, it looks like KeeFox has very primitive behaviour when for deciding whether a submitted form is a potential new login, and also when deciding to autofill a form

In general, Firefox does a very good job of both these things with a low false-positive rate. I am providing some concrete examples of where KeeFox fails for really obvious reasons.

First case: KeeFox will attempt to fill in a form even if that form contains a single text field. It fills in the 'username' part, but where does the password go? It makes no sense.

Second case: KeeFox will ask if you want to save a new login when you submit a form containing one text (not password) field.

KeeFox will ask if you want to save a new login when you submit data from arbitrary forms that contain many form elements, including those of different types such as selects and textareas, and _even_ forms that don't contain a password field.

Is it possible to copy or better mimic Firefox's native behaviour in these cases?

**Comment by luckyrat** [comment]
Which KeeFox version are you using?

**Comment by BoffinbraiN** [comment]
KeeFox 1.5.4 on Firefox 44 for Windows 7.

**Comment by luckyrat** [comment]
KeeFox 1.6 should address some of these issues but it's always a balance. Last time I looked at the native behaviour, there were long lists of login forms that wouldn't work with it because it was too prescriptive, hence the more intelligent approach within KeeFox. I believe Mozilla are now starting to introduce custom rules for some websites so that might already (or at least eventually) lead to better behaviour in the places where KeeFox has historically performed better but that's a very expensive and somewhat fragile approach to addressing the lack of standard login form behaviour.

For example, we want a single text field to be filled in despite the lack of a password field because many login forms present a username field on one page and then a password (or two) on a subsequent page.

1.6 can be found here: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/beta

**Comment by BoffinbraiN** [comment]
I'm not sure what to suggest here, other than avoiding autofilling GET forms (already discussed that) and perhaps avoiding text fiends that don't conform to the list of common names/IDs of username/email fields. In my case, I had a GET form that had a single field called PropertyID and still ended up with my username being filled in.

For the case of longer, complex forms, you might want to see this bug report I filed recently. https://bugzilla.mozilla.org/show_bug.cgi?id=1247248

**Comment by luckyrat** [comment]
Avoiding text fields that don't match certain names doesn't work in many cases but the [site-specific config](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Tips-%7C-Site-Specific) could help you to work around issues with specific websites you visit.

KeeFox already considers the length of the form and the number of form fields it is able to fill in - we don't fill in forms where we have a low number of fields matched. It's not perfect (never can be) but it appears to solve the same issue you reported to Mozilla and this is the first complaint of long forms being incorrectly completed since KeeFox 1.5 introduced this change so considering how often it was mentioned previously, I think it's safe to say it's a lot better than it was a year ago.

#519 points to the flip-side of your suggestion - this improvement already comes with some side-effects so it's not practical to make it more aggressive across every website.
