### ISSUE TITLE
Max Length of input fields is ignored

### ISSUE THREAD

**Issue by bdurrer** [kee-org/KeeFox#646]
I am not entirely convinced if this really should be considered a bug. However, it does break websites.

**Issue**: When an value is longer than the maxlength of an inputfield, it gets inserted nonetheless. If a real user tries to type it, it's not possible to exceed the maxlength.

**Consequence**: You can enter passwords into registration / change password forms which are not processable by the system.
Its suprising how many websites trust the clients and don't validate the user input and just crop the input. 
**Result**: You cannot login anymore (unless you crop the password manually).

I suggest that KeeFox somehow reports when an input is forced into a field, which does not support that many characters.

Sample pages: battle.net account "change password" form.

**Comment by luckyrat** [comment]
Thanks for raising a good point. I agree it's worth discussing because it does result in confusing or even disruptive behaviour.

KeeFox doesn't automatically insert new passwords into fields - it's up to the user to paste them in. So I guess that your too-long password is truncated when you paste it into the form field. I don't think KeeFox could (or even should?) interfere with what is just standard copy/paste functionality - if anything should be warning you of this problem it should be Firefox I think.

These Firefox bugs are related to this issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=603190
https://bugzilla.mozilla.org/show_bug.cgi?id=613016

One thing KeeFox might be able to do is inspect the context of which form field is focussed when you use the right-click "generate password" option. If it finds a maxlength it could warn you or maybe attempt to adjust the password generation algorithm so you get the correct length in the first place. Honestly though I think this would be a bit too hidden to be useful - I know from our metrics collection that the use of this context menu option is very low compared to the more discoverable password generation button on the main menu. I think this sort of approach might only work if KeeFox were to take more direct responsibility for the change password process but I know that is an unrealistic feature to develop without the huge levels of ongoing funding available only to large corporates. Maybe that will change one day but it would require effort from website owners too so it's unlikely to happen this decade.

**Comment by bdurrer** [comment]
One thing is the password generator. There, you can generate a password which is too long and you probably won't notice it when you paste it into a registration form. Since it does not create an KeePass entry automatically, you might do that manually by pasting the PW into KeePass. You end up with KeePass entry, which does not match the website.

The real issue comes up later, when you try to login. One could naively assume, that KeeFox would fill in the cropped password - it won't. KeeFox (like JS and HTML <input value="12345"> elements) ignores the maxlength. Actually, only direct user input (like typing and copy+pastE) respects maxlength.

Personally, I think the warning would be very useful here, where KeeFox automagically enters data, ignoring validation rules, which the user cannot. I assume that KeeFox indeed knows what fields are here, since it does not change them by _typing _but by _inserting_ the values into the fields directly.

**Comment by luckyrat** [comment]
Makes sense. So we can essentially have a warning raised when KeeFox fills a field with a value longer than the maxlength attribute. It doesn't address the problem at its root but at least alerts users to the likelihood that they need to manually truncate the password stored in KeePass.

We might be able to go a step further and offer a way to automatically update the entry but as a first step I think a visible warning along these lines would help:

"KeeFox filled a field on this page with more characters than the website expects. Your login attempt may fail. If it does, you should remove the last n characters of the text/password in your KeePass entry so that there a maximum of m characters. \[The affected field is called <name>[(ID: <id>)]...] (we'll need a variety of output options based on whether the form field has a name/ID and whether the corresponding KeePass entry field has a name/ID and whether they matched the page field name/ID so the user can identify which of potentially multiple usernames and passwords are affected)"

We'll need a way to avoid this warning popping up everytime a user logs into a site which has accepted a stronger password than the maxlength attribute implies. I'm not yet sure whether a per-site setting would be best here or a flag in the KeePass entry.

It would be good to be able to be reset the warning exception state when a KeePass password/username is changed as a result of a website redesign.
