### ISSUE TITLE
Too many TCP connection attempts when KeePass is NOT started

### ISSUE THREAD

**Issue by ccleaud** [kee-org/KeeFox#652]
Hello,

I was wondering why my software firewall suddenly shows me dozen of TCP connections attempts.
I have KeeFox v1.6.0 installed on FireFox 45 (but I first detected this behavior 6 monthes ago).

After a quick analysis, I noticed that if KeePass is NOT started, KeeFox attempts to create a WebSocket connection every 200 ms.
Since KeePass is started, no new TCP connection is attempted.
Since KeePass is exited again, TCP connection attempts restart every 200 ms.

I've configured KeePass to listen on port 65535. Here is what ProcessHacker shows:
![keefox](https://cloud.githubusercontent.com/assets/7109720/14412555/65107f0a-ff65-11e5-85b1-e6fdd5b28972.png)

Can you make the 200ms settable as a settings?
Is there another means to detect whether KeePass is started?

Thanks,
Regards.

**Comment by luckyrat** [comment]
> Can you make the 200ms settable as a settings?

What would be the benefit of doing this?

> Is there another means to detect whether KeePass is started?

No. This is the only method that can work between a Firefox addon and KeePass plugin (apart from other TCP based connections... which won't really gain us any advantage).

**Comment by ccleaud** [comment]
Hi,

 

Thanks for your reply.

 

Allowing to change the delay between 2 websocket connection attempts would reduce, in my case, the connections count per second (5 per second is really too much).

**Comment by luckyrat** [comment]
KeeFox should attempt to connect every 250ms for about the first 10 seconds after it is installed. If you're seeing such regular connection attempts continue indefinitely then there may be a bug so I'll need more information about your system in order to try to reproduce it. An indefinite number of requests at this rate might cause the ephemeral TCP ports to be cycled through more quickly than normal but that shouldn't be a problem unless other programs have bugs; apart from that, I don't see why connection attempts at even 10 times this rate should be problematic. I benchmarked the performance impact of the current setting on an old PC 5 years ago and could detect no impact.

The normal behaviour is to attempt to connect once every 2000 milliseconds.

By the way, the websocket connection itself is only attempted about once per minute - the more regular attempts are basic HTTP connections.
