### ISSUE TITLE
Keefox does not work with referenced entries

### ISSUE THREAD

**Issue by sminjard** [kee-org/KeeFox#658]
In Keepass, you can reference entries so you can have one couple login/password that you can share along many other entries. It is useful if you have an account that is shared with many websites.

The prompt window does seem to feel properly, however, unless you rewrite the password manually, the login fails.

**Comment by dlech** [comment]
Can you give a concrete example of how to set up entries to reproduce the problem?

**Comment by sminjard** [comment]
- Right click on an entry
- click on "Duplicate Entry"
- check "Replace user names and passwords by reference"
- associate another website in the URL

It is useful for professional purposes when an account is managed by a database and a lot of websites are using the same account. But for the tests, the account database should not matter.

The problem has been detected when I tried to log in into Jira and Confluence websites of my enterprise. But try with any couple of websites, it should do the same since it is just information given through the message box popup window.

**Comment by sminjard** [comment]
Either you fixed the issue, or it only happen with password finishing by ~.

**Comment by GMTA** [comment]
I can confirm this issue. I have a Bitbucket entry with references username and password to my Atlassian account which is not found by KeeFox.

**Comment by Geobert** [comment]
Same issue here, I have my network router that can be accessed through a dns if my box is in modem mode (so my router does the routing) or through ip only if my box is in router mode (I have an issue with the box in modem mode, so I have to stick with router mode atm) instead of fetching the reference, it fills the fields with the reference ID.

My first entry is:
![image](https://user-images.githubusercontent.com/72570/39677719-9ce19c3c-5177-11e8-981e-061ea1136257.png)

do the manipulation described by sminjard above and you got something like:
![image](https://user-images.githubusercontent.com/72570/39677727-b93a33bc-5177-11e8-8e78-188fb765cce9.png)

The first entry has http://tplinkwifi.net as url and the second one has 192.168.1.1 as url.

And when filling the fields I got:
![image](https://user-images.githubusercontent.com/72570/39677734-ea598830-5177-11e8-9e9b-8049c4d942b2.png)

Instead of the proper user/password to be fetch from the original entry

**Comment by luckyrat** [comment]
See https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107
