### ISSUE TITLE
keefox only shows logins on perfectly matched URLs

### ISSUE THREAD

**Issue by space-potato** [kee-org/KeeFox#665]
It has always worked until a while. I used it on IceCat and worked perfectly, then I removed it (the whole browser). Now I've reinstalled it but once I did the install it started to only show me logins where the keepass url perfectly matched the url of the website. This has never been the case before and I haven't changed nothing in keepass

e.g
If I went to reddit.com before, I had various accounts.. some of them were registered with just the url "reddit.com", others with "https://reddit.com" and others with the "www" and everyone showed on the logins list. Now everyone must be registered with the URL "https://www.reddit.com" otherwise they won't be showed.
As I said nothing's changed on KeePass. At first I though that I should have upgraded to 2.33, but even after the upgrade and a clean install I'm having the same problem

**Comment by luckyrat** [comment]
KeeFox's default behaviour is to match everything with the same domain (so reddit.com in this example) and same protocol (http / https). You can change that for specific entries - see https://github.com/luckyrat/KeeFox/wiki/en-%7C-Using-KeeFox-%7C-Alternative-URLs 

I'm not aware of any other way that the behaviour could change in the way you describe but if you can provide some steps for someone else to follow in order to reproduce the problem we could try to get to the bottom of it.

**Comment by freeasinbear** [comment]
I checked and every entry has the domain option, so it should work independently from the rest of the URL right?

**Comment by luckyrat** [comment]
Yeah that's right. Check that the URLs are valid too - "www.reddit.com" isn't a URL but "https://www.reddit.com" is for example.

**Comment by freeasinbear** [comment]
I tried to use only "github.com" and it seems to work.. 
When I tried with reddit, I used some accounts with different URLs, but it only showed the "exact" ones (with the https://www").. maybe when it has different, it picks the full URL by default, regarding the settings?
