### ISSUE TITLE
Remove forced KeePass download and install.

### ISSUE THREAD

**Issue by space-potato** [kee-org/KeeFox#666]
KeeFox everytime tries to force me to install KeePass even if I already have it installed. It's totally non-intuitive and I think everyone who installas KeeFox already has KeePass installed, so it's redundant.
Everytime I install it I have to stop the automatic install, even if I set the KeePass folder path and choose the other option. 

My suggestion: just put a button that asks you to choose your folder path, portable or not. Don't force any download and install; we come to install KeeFox because we already have KeePass, not vice versa

**Comment by luckyrat** [comment]
> KeeFox everytime tries to force me to install KeePass

I don't understand I'm afraid. This doesn't happen on any of my test machines and I've never heard of anyone else's KeeFox installation forcing them to install KeePass every time so we'll need a lot more information if we're going to be able to change whatever is happening on your system.

> I think everyone who installas KeeFox already has KeePass installed

What makes you think that?

**Comment by freeasinbear** [comment]
No matter what I choose, custom path or not, it keeps trying to download and install the non-portable KeePass.. sometimes I just cancel the install and then it starts installing the plugin in the right path, but other times it messes up a bit and doesn't work (I tried several times to be able to have a working install)

> What makes you think that?

Just my opinion/impression.. I think it's more natural that people that already have KeePass search KeeFox to be able to link the Password Manager in Firefox and not vice-versa.. maybe you have statistics about downloads that may have been done as an extra, "forced", like it is happening to me?

**Comment by luckyrat** [comment]
The download part I can understand - we optimise the path for new KeePass users so the KeePass installer is downloaded if we don't detect an existing installation. The theory is that a few MB of unnecessary data usage for existing users is a small price to pay in order to speed up and smooth out a relatively complex setup procedure for new users.

What's more strange is that you are then forced to execute this downloaded KeePass installer even when selecting the option to pick an installation location. I'm out of spare time for now but can try to review the install code soon in case I can spot anything that might explain that behaviour.

**Comment by freeasinbear** [comment]
Thanks a lot for your time! If you need further information to help recognize the eventual problem I'm here.

PS: I just tried to reinstall it, but with KeePass opened. It asked for the passcode without prompting me to the "welcome" page. After having linked it, I set the custom path (because otherwise I guess it would "forget" the KeePass install) and now seems to work (I have to hadd that I had unistalled it a while ago so I don't know if the old config files helped through the process(last time i made it work but decided to remove it because of #665)
