### ISSUE TITLE
Repeated request for FireFox Master Password when trying to conceal the KPRPC key username and password.

### ISSUE THREAD

**Issue by Papa-Gus** [kee-org/KeeFox#669]
I am evaluating KeeFox (v1.6), an add-on for FireFox, along with KeePass (v2.33) on a Windows 7 Pro (64 bit) machine and need clarification to an inextricable problem that appears to be receiving a lot of chatter but no explanation.

The way I understand it, KeeFox communicates with KeePass using the KeePassRPC plugin.  The KPRPC key exchanges a unique username and password that is stored within FireFox’s “Saved Logins”.  The “Saved Logins” dialog box reveals the KPRPC key username and password for any user to see.  To me, this appears as a security issue.  I can create a FireFox Master Password, without enabling the “Remember logins for sites” feature, to conceal the KPRPC key username and password; this seems to correct the issue.  However, when I start the first FireFox session it presents me with a screen to enter the FireFox Master Password; doing so repeats the problem previously stated.  If I ignore the nag screen by canceling the request to enter the FireFox Master Password, it will prompt me again within ten seconds and is relentless in this quest.

How do I keep the KPRPC key username and password concealed and completely stop the nag screen from being displayed?

**Comment by luckyrat** [comment]
> a unique username and password that is stored within FireFox’s “Saved Logins”. 

Kind of. Take a look at the manual for the complete picture: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Technical-%7C-KeePassRPC-detail#connection-security

> To me, this appears as a security issue.

Why? It's worth reading the introduction to KeePassRPC if you haven't already since that will give you some good background information to help you answer that question: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Technical-%7C-KeePassRPC

> How do I keep the KPRPC key username and password concealed and completely stop the nag screen from being displayed?

If you're primarily interested in the highest possible security of this KeeFox traffic across your localhost network you should use the High security option which should give you a similar end-result to what you're trying with the Firefox master password.
