### ISSUE TITLE
Option to disable automatic form filling and submition when in private browsing mode

### ISSUE THREAD

**Issue by luckyrat** [kee-org/KeeFox#670]
Given Firefox's recent expansion of the private browsing feature to make it more difficult for websites to track users while browsing, we could consider modifying KeeFox so that it doesn't automatically reveal identities to the websites that the user has an account for.

I think it's quite an edge case in terms of a privacy concern but will bear it in mind for a future enhancement and wanted to post the idea in case anyone else wants to comment.

**Comment by zeroepoch** [comment]
After creating a Zoho account it doesn't let me reply to any discussion on the Forum but I wanted to comment on https://zohodiscussions.com/keefox#Topic/71684000000906013. I agree with Mark Bee about the auto-fill (or auto-submit really).  While it's less of a security concern to auto-fill from a URL in your password database I find it often breaks the website.  I'd rather it in general just attempt to auto-fill but never submit regardless of how I use it because I may want to correct KeeFox or check the remember me box.  I use KeeFox as a convenient interface to avoid needing to use 2 different apps back and forth, but I want all things password related to be more explicit rather than implicit.  Yes I know this is not directly related to this issue but this issue was referenced by the above forum topic.
