### ISSUE TITLE
The second tab on the tabbar is not displayed

### ISSUE THREAD

**Issue by phts** [kee-org/KeeFox#706]
There is a strange bug with KeeFox. Tabbar is partially broken with the extension. The second tab is not displayed.
1. Open a newly created empty profile
2. Settings -> When Firefox starts -> Show my windows and tabs from last time
3. Make 3 tabs (e.g. google "111", "222", "333")
4. `about:config` -> `xpinstall.signatures.required` -> `false` (to be able to enable the extension)
5. Install KeeFox extension
6. Restart browser

After restart there is a "Setup KeeFox" page opened. Login is not required for now to reproduce the bug.

"222" page now is gone from the tabbar. However it can be reached by using `ctrl+tab` hotkeys. And it cannot be closed.

If move some tab to the first position (new order will be e.g. "333" "111" "222") and restart the browser then "222" is now displayed but the tab that was on the second position ("111") is now gone.

Sometimes it starts working normally but sometimes the bug appears again.

Browser console (`ctrl+shift+J`) seems to be silent.

When disable KeeFox plugin then all tabs will be displayed correctly. Enable - the buggy behavior.

It seems this bug [is also mentioned](https://github.com/luckyrat/KeeFox/issues/471#issuecomment-170660758) by @boldt in #471.

---

Reproduced in [Firefox ESR 45](https://www.mozilla.org/en-US/firefox/organizations/faq/) on Debian and Windows on several profiles.

**Comment by stampjp** [comment]
This problem is also exhibited in Firefox 49.0.1 on Windows 10 both with and without anniversary update. Firefox also has Tab Mix Plus and Tree Style Tab and effecting the tabs. The 2nd tab is not visible, but leaves a blank space. Clicking in the blank space does bring up the page that should be shown in the tab. So it is the description that is missing and the tab with its X. If the tab is a tree and the tree is collapsed, clicking causes the children, but not the parent of the tree, to display. Just blank.

**Comment by phts** [comment]
Not actual noeadays. Closed.
