### ISSUE TITLE
Setup KeeFox tab is opened every time I start firefox

### ISSUE THREAD

**Issue by umglurf** [kee-org/KeeFox#711]
The setup tab with installations instructions is starting every time I'm starting firefox, even though the Keepass plugin is installed and KeeFox works fine.

**Comment by david-caro** [comment]
Same for me :cry:

**Comment by david-caro** [comment]
I'm running keefox 1.6.3 on firefox 48.0.1 on fedora 24

**Comment by Nama** [comment]
Came here to report this, happens to me, too.
The more annoying thing is, that after closing, there is still a invisible tab opened.
I need to move a tab to a new windows to get rid of the invisible one.

**Comment by thomasrebele** [comment]
I also have the problem with the always opening Setup KeeFox tab. Could you add an option to disable this tap?

**Comment by apelly** [comment]
I solved this issue myself, again, yesterday.

1) you need package mono-complete, technically not all of it, but this'll solve your problem quickly.
2) add your keepass directory /usr/lib/keepass2 to the options dialog
3) stick the plugin in that keepass directory

_It would be helpful in the extreme to have those notes in that setup keefox tab that shows up._

I have many computers and use keepass on all of them. All but 1 (2 since yesterday) have this issue because time is short and there are bigger issues to solve. The google clue for this wasn't easy to find, and the guy who write the page concludes it wasn't worth his time.

**Comment by Nama** [comment]
Yes, this fixed it.
On Arch there is no mono-complete and **mono is enough**.

You need to set `/usr/share/keepass/` as the _keepass-path_ and `/usr/bin/mono` for _mono_.

**Comment by umglurf** [comment]
This fixed it for me to, but as apelly wrote, this should be in the setup page

**Comment by nsubiron** [comment]
I was having this issue for a while, apparently Keefox expects the "plugins" directory to be all lower case but in newer versions of Keepass the folder is called "Plugins". Renaming seems to work fine.

**Comment by dlech** [comment]
> apparently Keefox expects the "plugins" directory to be all lower case but in newer versions of Keepass the folder is called "Plugins"

Related: #745

**Comment by wokeaf** [comment]
Thanks @apelly! 

add your keepass directory /usr/lib/keepass2 to the options dialog
^ 
This worked for me.

**Comment by seiferflo** [comment]
Thanks for the tip @wokeaf , It was driving me nuts as that tab was freezing firefox everytime I tried to close it or open it.

**Comment by wrt54gl** [comment]
Thanks @nsubiron and @apelly 

I just added the /usr/lib/keepass2 to the options and put added a symbolic link.

On Debian 9:

cd /usr/lib/keepass2/
ln -s Plugins plugins
