### ISSUE TITLE
Keefox in Thunderbird: credentials  are only partly remembered

### ISSUE THREAD

**Issue by fouvry** [kee-org/KeeFox#715]
I'm using Keefox (1.6.3) in Thunderbird (45.4.0). Thunderbird contains four mail accounts, and for each of them the authentication behaves slightly differently. For three of them, I need to give the login information twice, and the most annoying thing is that the second time it does not find any matching account information. I've configured the entry with imap and smtp server information.

Is there any way to debug that?

Thanks!

**Comment by dlech** [comment]
Can you post screenshots of the dialog boxes?

**Comment by fouvry** [comment]
This is the window I get first

![Authentication Required](http://daccord-sb.de/~ff/window-1.png)

After that, I get the following:

![Mail Server Password Required-edited.png](http://daccord-sb.de/~ff/window-2.png)

**Comment by dlech** [comment]
I'm not sure why you are getting two dialogs. Maybe there is a proxy that requires a password?

The SMTP dialog will not be shown until you try to send an email.

The second one is the IMAP dialog. It is looking for an entry in KeePass that has Username that matches the first blackout and a URL that matches the second blackout.

Depending on your settings just a hostname may be enough to match or if you have set it for exact matching, the URL should be something like `imap://imap.gmail.com`

You can add additional URLs on the URL (sub)tab of the KeeFox tab in KeePass. If you need different usernames for matching, you will have to create a second entry.

**Comment by dlech** [comment]
Due to the recent split between Thunderbird and Firefox extensions, we have started a fork of KeeFox specifically for Thunderbird. We are calling this new extension KeeBird and the code and issue tracking are now in a new GitHub repository. If anyone is still interested in getting this issue resolved, please let us know by opening a new issue at https://github.com/kee-org/keebird/issues and copy/paste any relevant information (or at least link to this issue).
