### ISSUE TITLE
Better support for "character 1, 4, and 7 of your password"

### ISSUE THREAD

**Issue by alansingfield** [kee-org/KeeFox#718]
Many sites want you to enter the 1st, 4th, 7th chars of a password.
`[ ]**[ ]***[ ]*******`

When displaying the password in the Edit box, have an option to display the password character by character to avoid having to count to find the position(!)

`01|02|03|04|05|06|07|08|09|10|11|12|`
`a | b| c| d| e| f| g| h| i| j| k| l|`

**Comment by r2evans** [comment]
I've seen this "partial password feature" on a couple of websites. The intention is to "authenticate the user" without requiring the full password, perhaps for online chat. Whether this is for convenience or risk mitigation (not passing a full password) is not important.

Instead of improving security, I feel partial-password indicates a *reduction* in security: by being able to match a substring of the password (whether or not contiguous), it indicates that the password is stored verbatim (cleartext) in the auth database.

My understanding of "good" password systems ("good" is subjective, perhaps) is that, during a password set/change, the cleartext password is hashed or encrypted with a system-private salt or key. This hash or crypttext is stored in the authdb. This way, even if the contents of the database are stolen, it will take considerably more work for the thief to be able to use the password fields. When a user provides a password for authentication, it is again hashed/encrypted using the same salt/key and it is the resulting string that is compared with what was stored previously. This practice is prevalent in high-security authentication systems such as Kerberos and the age-old `/etc/passwd` passwords.

I'm not a dev here nor even an influential person in this case, but I suggest it is more appropriate to discourage this "feature", and provide feedback to the providers using it that it is undesirable. An alternative to what I think is the perceived requirement/need is a phone-pin or secondary pass phrase on which they can use this partial-match technique. Using it on the primary authentication password is just too much risk, IMO.

**Comment by alansingfield** [comment]
Aha - think you might have misunderstood what I was asking for. This is when you have already entered your master password and we are now doing a "show password" on an individual website's entry. E.g. "Show me my password for abc.com".

I definitely agree that the WHOLE master password must be entered rather than just a few characters from it - I've been trying to think of how you might do this without just storing individual chars (or 3-character triplets) - whichever way you do it it doesn't feel secure.

**Comment by r2evans** [comment]
I think what you mean is to add indexes to "show password" so that, when websites ask for the *n<sup>th</sup>* character(s), you can more easily find it/them. I dislike having to count out my password characters, so I can see myself using that feature.

My point is that I want to discourage the behavior and not even suggest (by enabling it) that it is good practice. I'm suggesting that *despite* the convenience that this will certainly provide, I argue that this is a matter of principle. (If implemented, I'd ask that it have a clear warning/caveat indicating its security implications.)

> \<soapbox>
>  
> It has nothing to do with the user's storage of it (we always (?) store the entire password), nor with the medium over which the password is sent (I'm assuming well-encrypted or direct-entry). It has more to do with the server-side implementation and storage.
> 
> Let's assume that the website's database that stores our authentication credentials *will* be broken into and our records will be attained for nefarious intents. If the website supports "*n<sup>th</sup>* characters", it is storing the password in cleartext<sup>[1]</sup>. Once stolen, all records are instantly usable, requiring no further time or computing resources. If the passwords are stored encrypted/hashed, then the thief must attack the password fields (dictionary or brute-force). Given sufficient time and resources, they will theoretically be able to break all passwords; I can only hope that the exploit/theft will be noticed and passwords changed before the crypttext is broken.
> 
> If more and more password-managers (and proxies for them) support this feature, it's possible (even likely) that more websites will implement it in their auth systems<sup>[2]</sup>. (That is, unless they are as [tin-foil-hat paranoid](https://en.wikipedia.org/wiki/Tin_foil_hat) as I am :-).)
> 
> \</soapbox>

Notes:

1. I admit that it's possible that the website stores in cleartext *only* the *n<sup>th</sup>* characters, not the entire password, in which case this is slightly "less bad". Since it does effectively reduce the entropy of the whole password for brute force attacks, it's still "bad".
2. Consider other techniques such as 2FA and such. As it becomes easier for users to have a TOTP/HOTP device, more websites are implemented it as a second form of authentication. Anecdotal and not conclusive, just suggestive.
