### ISSUE TITLE
Updating KeeFox with Thunderbird only

### ISSUE THREAD

**Issue by wahwahbinx** [kee-org/KeeFox#738]
Hello,

First of all, thank you very much for this most useful add-on!

Now, I only use Thunderbird (currently 45.5.0, Win10 x64), but ditched Firefox a while ago. This is problematic whenever an update affects both the KeeFox add-on and the plugin: KeeFox stops working with Thunderbird altogether.

The solution is to install Firefox with KeeFox, close KeePass, and follow the update instructions. As I have no use for Firefox, this is not ideal. Could you please implement a solution for the sake of Thunderbird-only users?

Many thanks in advance!

**Comment by dlech** [comment]
Due to the recent split between Thunderbird and Firefox extensions, we have started a fork of KeeFox specifically for Thunderbird. We are calling this new extension KeeBird and the code and issue tracking are now in a new GitHub repository. If anyone is still interested in getting this issue resolved, please let us know by opening a new issue at https://github.com/kee-org/keebird/issues and copy/paste any relevant information (or at least link to this issue).

P.S. the KeePassRPC plugin for KeePass no longer needs to be updated each time the Thunderbird extension is updated. If you have update notifications enabled in KeePass, it will tell you when a new KeePassRPC version is available.
