### ISSUE TITLE
KeeFox Does not Launch KeePass

### ISSUE THREAD

**Issue by mikef187** [kee-org/KeeFox#745]
Fresh install of Debian Stretch.

**VERSIONS**
Firefox ESR ---- 45.5.1
KeeFox ---------- 1.6.4
KeePass2 ------- 2.34

**PROBLEM**
Copied KeePassRPC.plgx to /usr/lib/keepass2/Plugins/ as per normal install procedures. 
Entered /usr/lib/keepass2/ in KF Options for KP location.
Open FF and KF only has "Install KeePass" Button
Open KeePass app and KF connects successfully.
 Close KP and KF is back to "Install KP"

**SOLUTION**
Debian Stretch's install of KP creates folder /usr/lib/keepass2/Plugins/
in previous versions the folder is /usr/lib/keepass2/plugins/ Note Capital P

Rename Plugins to plugins, and FF+KF+KP function normally.
KF Gives "Launch KeePass" Button as expected.

`sudo mv /usr/lib/keepass2/Plugins/ /usr/lib/keepass2/plugins/ `

**ANOTHER ISSUE** (maybe related.)

While KeePass closed, /var/log/syslog gives 
`firefox-esr.desktop: loadInfo is null for channel http://127.0.0.1:12546/`
every 2 seconds, filling log files.
KF log gives 
`DEBUG: HTTP connection refused. Will not attempt web socket connection.`
every 2 seconds.

**Comment by mikef187** [comment]
I have submitted a bug report to debian as well 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848837

**Comment by dlech** [comment]
"plugins" (lower case) is hard coded in KeeFox. Unfortunately, if we change it, we break existing users of KeeFox.

Suggested workaround: use a symlink...

     sudo ln -s /usr/lib/keepass2/Plugins /usr/lib/keepass2/plugins

I will submit a patch to debian to do this automatically in the keepass2 package.

**Comment by mikef187** [comment]
Thank you for the quick response. A symlink is a good workaround, and I
will use it.

What about FireFox logging KeeFox''s failed connections to KeePass.
I have 14 thousand log entries just from today.

Dec 19 02:52:32 laptop firefox-esr.desktop[18135]: loadInfo is null for
channel http://127.0.0.1:12546/

**Comment by dlech** [comment]
> What about FireFox logging KeeFox''s failed connections to KeePass. I have 14 thousand log entries just from today.

I would suggest opening a new issue for that with some more details.

**Comment by juliantaylor** [comment]
can you explain why fixing the casing would break existing users? I'd rather see plugins fixed than adding symlinks every permutation of casing plugins might use.

**Comment by dlech** [comment]
This particular FireFox plugin (not KeePass plugin) is hard coded to look for KeePassRPC.plgx in `plugins/`. If we changed it to use the "correct" `Plugins`, then when the FireFox plugin is automatically updated, it breaks their installation. I haven't looked at the code hard enough, but I suppose it might be possible to change the FireFox addon to look in both places.

> I'd rather see plugins fixed than adding symlinks every permutation of casing plugins might use.

We certainly don't need every permutation. `Plugins` and `plugins` pointing to the same directory will fix 99+% of use cases.

I also have a ppa for KeePass plugins. They are all installed in `plugins/`. But now that I am thinking about it more, if the `keepass2` package tried to create a symlink there, it would fail because there is an existing directory. So, I guess that what I thought would be a simple fix is not so simple.

**Comment by juliantaylor** [comment]
patching keepass to check both directories might be an option

**Comment by dlech** [comment]
KeePass already does this (otherwise my ppa plugins would be broken already). The problem here is that we need to make the KeeFox FireFox plugin do the same.
