### ISSUE TITLE
KeeFox not detecting already started Keepass

### ISSUE THREAD

**Issue by balasankarc** [kee-org/KeeFox#752]
OS: Debian Sid  
Keepass: v2.34  
KeeFox: v1.6.4

KeeFox only detects Keepass if it is started using `Launch Keepass` button and not if it is opened manually before starting Firefox.

Because of this, I can't add Keepass to my startup applications and automate it.

**Comment by gkaklas** [comment]
Judging from the [Debian package](https://packages.debian.org/jessie/all/keepass2/download), the Debian desktop file (`/usr/share/applications/keepass2.desktop`) launches KeePass by running `exec /usr/bin/cli /usr/lib/keepass2/KeePass.exe "$@"`. In KeeFox, try setting:

* Mono executable location: `/usr/bin/cli`
* KeePass installation location: `/usr/lib/keepass2`

(In case this is helpful to the developer: I'm using ArchLinux and I don't have this problem -- probably because the desktop file uses `/usr/bin/mono`, which is the default)

**Comment by Dimas-sc** [comment]
Same here since Keepass 2.35

**Comment by balasankarc** [comment]
@gkaklas No. I am not opening keepass from desktop file. I use command line to start Keepass2 and both the locations of Keepass and Mono are set properly in KeeFox. So, no. It isn't the issue of configuration, AFAIK.

**Comment by vanous** [comment]
No problem here on Debian:
cat /etc/debian_version 
9.0

keepass2 --version
KeePass 2.35

ps ax | grep KeePass
25592 tty2     Sl+    0:05 /usr/bin/cli /usr/lib/keepass2/KeePass.exe

settings in KeeFox:

/usr/bin/mono

/usr/lib/keepass2/

hope this helps
P.
