### ISSUE TITLE
Keefox + Thunderbird for Chat account ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [kee-org/KeeFox#768]
Hello,

Password for smtp/imap account are well recognized from my thunderbird (like expected here : https://github.com/luckyrat/KeeFox/wiki/fr-%7C-Thunderbird ).

But not the password of my chat (jabber/xmpp) account is not recognized/used. Is there a trick to make it work ?
I already tried to specify in URL field of my password the address of the IM server.

Regards.

**Comment by dlech** [comment]
I'm guessing KeeFox does not recognize the text in the dialog box. Can you post a screenshot?

**Comment by GuiGuiSoft** [comment]
Of course, here it is :
![capture](https://cloud.githubusercontent.com/assets/8069239/24287876/a5860460-107b-11e7-88f2-38151867f580.PNG)

**Comment by dlech** [comment]
I suppose this could be another case of renamed string resources, but it could be some resource that we just are not testing for. Either way, someone will need to dig around in the DOM and/or Thunderbird source code to figure it out. KeeFox will have to be changed to fix it.

**Comment by dlech** [comment]
I had a look at this, but it is not as simple as other password dialogs. This dialog has the user@host in the title. All other password dialogs have a fixed title, so the current code does a simple string comparison for the title. To make this work, the code would have to be modified to do a regex match of the title, being careful not to break any of the other matching.

I'm not really keen on doing this giving the uncertain state of both KeeFox and Thunderbird at the moment, but if anyone wants to give it a try, I have started a patch (linked above).

**Comment by dlech** [comment]
Due to the recent split between Thunderbird and Firefox extensions, we have started a fork of KeeFox specifically for Thunderbird. We are calling this new extension KeeBird and the code and issue tracking are now in a new GitHub repository. If anyone is still interested in getting this issue resolved, please let us know by opening a new issue at https://github.com/kee-org/keebird/issues and copy/paste any relevant information (or at least link to this issue).
