### ISSUE TITLE
KeeBird - fork for Thunderbird

### ISSUE THREAD

**Issue by dlech** [kee-org/KeeFox#769]
I just read <http://keefox.org/news/detail/2017/03/26/changes-to-keefox-in-2017>. I've also been kind of keeping up with Thunderbird development. Thunderbird will be supporting XUL extensions for the foreseeable future and will not be supporting WebExtensions. So, I would suggest/prefer creating a fork of KeeFox called KeeBird. We can strip out all of the FireFox stuff and have a Thunderbird only addon.

**Comment by luckyrat** [comment]
Thanks for the update, I did have a quick look for Thunderbird's plans but couldn't find anything through Google and Mozilla didn't seem to know either. I would have been very surprised if they planned to utilise WebExtensions though!

Do you know anything about how they will handle the changes to AMO later in the year? Mozilla currently prevent WebExtensions add-ons from also hosting XUL files so unless that changes, a forked version hosted under a new add-on ID would probably be the only option, but I'm certain KeeFox is far from the only add-on that will be interested knowing how to best maintain a WebExtension for Firefox and XUL addon for Thunderbird/other browsers. For some add-ons, having to fork with a new name for an established Thunderbird version could not be a desirable outcome so they might be able to offer some other options we could also take advantage of.

I'm wary of making a change without adequate planning and notification though. It looks like there are around 1000 Thunderbird users at the moment so it would be nice to be able to get a message to them one way or another as part of the 1.7 release. If we have established by then that they will have to take manual steps to download the addon from some other add-on repository, we should let them know in advance. Or if we have to wait until nearer November to do this, we could release a 1.8 version to help migrate Thunderbird users (I want to get the 1.7 version out fairly early to help with data migration for Nightly users that could find they're forced to use a 2.0 alpha in the summer).

It might be sensible for a forked version to be contained within the kee-org organisation - I could create a repository called `thunderbird-addon` and give you admin rights if we decide that forking is the best move for Thunderbird users.

It's also worth noting that I'm intending to make KeePassRPC an updatable plugin from within KeePass (with code in a [separate repo](https://github.com/kee-org/keepassrpc)). KeeFox will have to negotiate with it on startup and at necessary points during execution in order to find out whether the installed version of KeePassRPC is compatible for the given KeeFox feature (sometimes vice-versa?) and I suspect any KeeBird fork would need to do the same (especially if we make changes to KeePassRPC in future to improve thunderbird-related functionality). Overall I suspect that'll simplify things for Thunderbird users, especially those that use Firefox too - far fewer (maybe even no) situations where the user will hit problems because of not updating all versions of the browser/Thunderbird add-on at the same time.

**Comment by dlech** [comment]
> Do you know anything about how they will handle the changes to AMO later in the year?

They are thinking they will have to fork and maintain their own extensions infrastructure, including the website and getting their own reviewers.

> I'm wary of making a change without adequate planning and notification though.

I think your plan sounds good.

> It might be sensible for a forked version to be contained within the kee-org organisation

:+1:

> It's also worth noting that I'm intending to make KeePassRPC an updatable plugin from within KeePass

I was thinking along the same lines. It would be nice to keep the version requirement one-way. That is, the client programs have a `requiresKeePassRPC(version)` function. If KeePassRPC is not new enough, then the client notifies the user to upgrade the KeePass plugin. We will just have to be careful not to make breaking changes in the protocol so that it always stays backwards compatible.

**Comment by luckyrat** [comment]
> I was thinking along the same lines. It would be nice to keep the version requirement one-way. That is, the client programs have a requiresKeePassRPC(version) function. If KeePassRPC is not new enough, then the client notifies the user to upgrade the KeePass plugin. We will just have to be careful not to make breaking changes in the protocol so that it always stays backwards compatible.

Yeah that's an option. I'm going to experiment with using a system of negotiated feature flags first since that should give a little more future flexibility but if that proves too difficult in some or all cases, a one-way version requirement would be a good middle-ground I think. See #762

**Comment by dlech** [comment]
This is a done deal. https://github.com/kee-org/keebird
