### ISSUE TITLE
Critical: KeeFox 1.7.0 is unavailable to install from addons.mozilla.org in FF 54+

### ISSUE THREAD

**Issue by BoffinbraiN** [kee-org/KeeFox#802]
The Mozilla addons page says KeeFox is "not compatible with your version of Firefox" when trying to install it on a new browser profile, even though it was already installed and working fine on other profiles.

When on the Versions page, it says the following:

Version 1.7.0
Released June 3, 2017
Works with Firefox 32.0 - 51.\*, Thunderbird 32.0 - 51.* 

However, the previous version is available for some reason...

Version 1.6.4
Released November 19, 2016
Works with Firefox 32.0 - 56.\*, Thunderbird 32.0 - 51.*

I tried that version but because KeePass was already on 1.7.0 nothing worked. I had to force-install 1.7.0.

Are you able to get the metadata corrected on AMO? This will stop new users from being able to use KeeFox!

**Comment by luckyrat** [comment]
Thanks for letting me know. Looks like a bug on AMO has caused the current version 1.7.0 to be incorrectly marked as incompatible. They are making lots of changes now in order to try to force users towards WebExtensions addons rather than legacy addons like KeeFox 1.7 so I guess they messed something up in that process.

I've worked around the issue by manually adjusting the list of available versions which seems to have fixed the immediate problem. Let me know if you still have issues with it.

**Comment by Dema** [comment]
Also, Firefox 54.0 Build Id: 20170612121707 (Ubuntu) disabled addon and wants it to be signed.

**Comment by BoffinbraiN** [comment]
I'm assuming this would have effected any Firefox from 52 onwards, given the metadata.
The info now says up to 56.* so yes, the button is enabled now. That should keep us going for a little while longer!
How is KeeFox 2.0 looking? Will it be using WebExtensions? :)

**Comment by luckyrat** [comment]
kee-org/browser-addon#1
