### ISSUE TITLE
Thunderbird doesn't search for LDAP passwords

### ISSUE THREAD

**Issue by baztian** [kee-org/KeeFox#809]
KeeFox's matching doesn't seem to be implemented for address books based on LDAP. I'm asked to provide a password for the LDAP server but there is no message like "No matching entries found".

Please implement LDAP url matching.

**Comment by dlech** [comment]
Due to the recent split between Thunderbird and Firefox extensions, we have started a fork of KeeFox specifically for Thunderbird. We are calling this new extension KeeBird and the code and issue tracking are now in a new GitHub repository. If anyone is still interested in getting this issue resolved, please let us know by opening a new issue at https://github.com/kee-org/keebird/issues and copy/paste any relevant information (or at least link to this issue).
