### ISSUE TITLE
In Thunderbird, Keefox is not using the full URL when requesting credentials from KeyPassRPC

### ISSUE THREAD

**Issue by ZaubererMD** [kee-org/KeeFox#810]
I have a few calendars synced with Thunderbird Lightning and would like Keefox to autofill and submit the credentials needed to access those (HTTP Auth). The Problem is that two of those calendars are hosted on the same domain (no subdomain), but with different paths and I need different credentials for the two.

The Thunderbird password prompt only lists the protocol and domain name, but not the path and I guess that is the information Keefox uses to get the credentials from keepass. Setting the correct Auth Realm in Keepass did not work either since Thunderbird does not event display that.

If Keefox would use the full URL of the calendar and not just the domain to get credentials from KeePass then this would work.

EDIT: I have checked the log, both entries have the same relevance (30), even though there should be a clearly more relevant one since I have the full URL set for the entries in KeePass.

**Comment by dlech** [comment]
Due to the recent split between Thunderbird and Firefox extensions, we have started a fork of KeeFox specifically for Thunderbird. We are calling this new extension KeeBird and the code and issue tracking are now in a new GitHub repository. If anyone is still interested in getting this issue resolved, please let us know by opening a new issue at https://github.com/kee-org/keebird/issues and copy/paste any relevant information (or at least link to this issue).
